version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-local
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins-jobs:/var/jenkins_home/jobs
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Djenkins.plugins.git.GitSCMTool.ALLOW_LOCAL_CHECKOUT=true
    user: root

  # Your existing dashboard services
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ci-dashboard-backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///app/data/ci_dashboard.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ci-dashboard-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  jenkins_home:

networks:
  default:
    name: ci-dashboard-network
