version: "3.9"

services:
  backend:
    build: 
      context: ./backend
      target: production
    container_name: ci-dashboard-backend-prod
    restart: always
    env_file: .env
    ports:
      - "${BACKEND_PORT:-8001}:8001"
    volumes:
      - prod_db_data:/app/data
      - ./logs:/app/logs
    networks:
      - dashboard-prod-network
    environment:
      - SQLALCHEMY_DATABASE_URL=sqlite:///./data/dashboard.db
      - LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  frontend:
    build: 
      context: ./frontend
      target: production
    container_name: ci-dashboard-frontend-prod
    restart: always
    env_file: .env
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - dashboard-prod-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.1'

  # Optional: Reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: ci-dashboard-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - dashboard-prod-network
    profiles:
      - with-proxy

volumes:
  prod_db_data:
    driver: local

networks:
  dashboard-prod-network:
    driver: bridge
